export const quotes = [
    "Napij se 💧",
    "Protáhni se 🙆",
    "Vypni hlavu 🔌",
    "Zhluboka se nadechni 🌬️",
    "Voda dělá zázraky ✨",
    "Vstaň a narovnej se 🧍",
    "Napiš někomu SMS 💬",
    "Už jsi dnes volal/a babičce? ☎️",
    "Pusť ramena dolů ⬇️",
    "Protáhni krk. Pomalu 🦒",
    "Už jsi dnes pil/a vodu? 💧",
    "Objednej si jídlo 🍽️",
    "Zvedni ruce nad hlavu 🙌",
    "Chvilku jen dýchej 😮‍💨",
    "Nohy chtějí pohyb 👣",
    "CaCall dnes proběhl? ☕",
    "Napij se znovu. Fakt 💧",
    "Změň polohu 🔄",
    "Odejdi od obrazovky 👀",
    "Usměj se. I jen trochu 🙂",
    "Protáhni záda 🦴",
    "Napiš 'jak se máš?' 💌",
    "Neřeš nic důležitého 🛑",
    "Dopřej si ticho 🔕",
    "Voda první. Všechno ostatní potom 💧",
    "Pohni se. Jen maličko 🕺",
    "Pauza je tvoje 🌿",
    "Nezapomeň jíst 🍎",
    "Hlava off 🔇",
    "Teď si opravdu odpočiň 🌙",
    "Napij se. Teď 💧",
    "Protáhni se, dřevo 🪵",
    "Vypni mozek. Aspoň na chvíli 🔌",
    "Narovnej se. Fakt 😐",
    "Přestaň civět do obrazovky 👀",
    "Zvedni zadek 🪑",
    "Sedíš tu jak inventář 🪑",
    "Napiš někomu. Někomu normálnímu 💬",
    "Objednej si jídlo. Hlad dělá blbce 🍕",
    "Volal/a jsi už babičce? Tak šup ☎️",
    "Napij se. Nebo umři 💀",
    "Protáhni se, než zatuhneš navždy 🗿",
    "Tělo stávkuje 🦴",
    "Narovnej se. Rakve jsou až potom ⚰️",
    "Voda. Protože ještě chceš žít 💧",
    "Vstaň. Smrt je zatím jen metafora 💀",
    "Zatuhneš. Víš to 🧊",
    "Mozek OFF 🧠",
    "Dýchej. Zatím 🌬️",
    "Napij se. Zase 💧",
    "Protáhni krk. Praská 🦒",
    "Sedíš si pro diagnózu 🪑",
    "Pauza, nebo bolest 🛑",
    "Vypni hlavu 🔇"
  ];
  